fix(ENB-83 PR-CHECK): PR commit validation flow

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -30,10 +30,10 @@ jobs:
         id: pr_conventional_regex_pattern
         run: |
           # Regex pattern
-          if [[ $JIRA_PROJECT_PR_TITLE_SCOPE != "" ]]; then
-            PATTERN='^(${{ inputs.pr_title_type  }})(\((${{ inputs.jira_project_pr_title_scope }})\-[0-9]+\))(!)?:\s?.+$'
+          if [[ "${JIRA_PROJECT_PR_TITLE_SCOPE}" != "" ]]; then
+            PATTERN="^(${{ inputs.pr_title_type }})\((${{ inputs.JIRA_PROJECT_PR_TITLE_SCOPE }})-[0-9]+\)(!)?:s?.+$"
           else
-            PATTERN='^(${{ inputs.pr_title_type }})(\([A-Za-z\-]+[0-9]+\))(!)?:\s?.+$'
+            PATTERN="^(${{ inputs.pr_title_type }})\([A-Za-z\-]+[0-9]+\)(!)?:s?.+$"
           fi
           echo REGEX PATTER is= ${PATTERN}
           echo "PATTERN=${PATTERN}" >> "$GITHUB_OUTPUT"
@@ -41,7 +41,7 @@ jobs:
       - name: PR Conventional Title check
         id: pr_title_check
         env:
-          PATTERN: ${{ steps.pr_conventional_regex_pattern.outputs.PATTERN}}
+          PATTERN: ${{ steps.pr_conventional_regex_pattern.outputs.PATTERN }}
         run: |
           PR_TITLE="${{ github.event.pull_request.title }}"
           echo "PR_TITLE: ${PR_TITLE}"
@@ -54,63 +54,49 @@ jobs:
             echo "✅ PR title format is valid."
           fi
 
+      - name: Fetch base and head refs
+        run: |
+          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
+          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
+
       - name: Get all commits in the PR
         # Run this step even if PR title check result is: failed
         if: ${{ !cancelled() || contains('failure', steps.pr_title_check.outcome) }}
         id: get_commits
-        uses: actions/github-script@v7
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const pr = await github.rest.pulls.listCommits({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              pull_number: context.payload.pull_request.number
-            });
-
-            const commits = pr.data.map(c => c.commit.message);
-            core.setOutput("MESSAGES", JSON.stringify(commits));
+        run: |
+          # Fetch the list of commits between the PR base and head
+          PR_COMMITS=$(git log origin/${{ github.base_ref }}..origin/${{ github.head_ref }} --pretty=format:%s)
+          echo "COMMITS<<EOF" >> $GITHUB_ENV
+          echo "$PR_COMMITS" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+          echo $COMMITS
 
       - name: Validate commit for Conventional Commit
         # Run this step even if PR title check result is: failed
         if: ${{ !cancelled() || contains('failure', steps.pr_title_check.outcome) }}
         id: pr_commits_check
         env:
-          PATTERN: ${{ steps.pr_conventional_regex_pattern.outputs.PATTERN}}
+          PATTERN: ${{ steps.pr_conventional_regex_pattern.outputs.PATTERN }}
         run: |
-          # Read all commit messages
-          echo "${{ toJSON(steps.get_commits.outputs.MESSAGES) }}"
-          echo $PATTERN 
-
-          # Convert JSON array to Bash array
-          printf '%s' "${{ toJSON(steps.get_commits.outputs.MESSAGES) }}" | jq -r '.[]' > commits.txt
-          echo JQ is done
+          echo echoing PATTERN
+          echo $COMMITS 
 
           INVALID=0
           echo "Checking commits..."
-
-          while read -r MSG; do
-            echo "➡️  $MSG"
-            if [[ ! "$MSG" =~ $PATTERN ]]; then
-              echo "❌ Invalid commit message: '$MSG'"
-              INVALID=1
+          echo "$COMMITS" | while IFS= read -r commit; do
+            echo "➡️ $commit"
+            if [[ ! "$commit" =~ $PATTERN ]]; then
+              echo "::error::❌ One or more commit messages are invalid. Expected format: <type>(<JIRA-TICKET>): <description>. Example: feat(ABC-123): add login functionality"
+              echo "### ❌ One or more commit messages are invalid" >> report.md
+              echo 'Expected format: \<type\>(\<JIRA-TICKET\>): \<message\>. Example: feat(ABC-123): add login functionality' >> report.md
+              exit 1
 
             else
               echo "::notice::✅ Valid commit"
             fi
-          done < commits.txt
-
-          if [ "$INVALID" -eq 1 ]; then
-            echo "::error::❌ One or more commit messages are invalid. Expected format: <type>(<JIRA-TICKET>): <description>. Example: feat(ABC-123): add login functionality"
-            echo "### ❌ One or more commit messages are invalid" >> report.md
-            echo 'Expected format: \<type\>(\<JIRA-TICKET\>): \<message\>. Example: feat(ABC-123): add login functionality' >> report.md
-            exit 1
-          else
-            echo "✅ All commits are valid."
-          fi
+          done
       - name: Comment the PR check fail result on to PR
         if: ${{ !cancelled() || contains('failure', steps.pr_title_check.outcome) || contains('failure', steps.pr_commits_check.outcome) }}
         uses: mshick/add-pr-comment@v2
         with:
           message-id: pr_commits_check
-          message-path: report.md
