feat(ENB-83 trivy-container-scan): container_scan monorepo support

diff --git a/.github/workflows/trivy-container-scan.yml b/.github/workflows/trivy-container-scan.yml
--- a/.github/workflows/trivy-container-scan.yml
+++ b/.github/workflows/trivy-container-scan.yml
@@ -11,6 +11,16 @@ on:
         description: "Action runner container image. Default = public.ecr.aws/studiographene/ci:node-20-alpine"
         type: string
         default: public.ecr.aws/studiographene/ci:node-20-alpine
+      is_monorepo_with_multi_dockerfile:
+        description: "Whether it is a monorepo with Dockerfile in differnet directories. If `true` repo will be searched for all the Dockerfile and scan performed on each. To scan only selected Docker file use input `dockerfile_paths`"
+        type: boolean
+        required: false
+        default: false
+      dockerfile_paths:
+        description: "Set of separated Dockerfile paths. Useful when you want scan Dockerfile in selected directories. Example: [./apps/users/Dockerfile, ./apps/account/Dockerfile]"
+        type: string
+        required: false
+        default: ""
       docker_build_command:
         type: string
         required: false
@@ -48,6 +58,7 @@ permissions:
 jobs:
   container_scan:
     runs-on: ubuntu-latest
+    if: ${{ !inputs.is_monorepo_with_multi_dockerfile }}
     container:
       image: ${{ inputs.action_runner_container_image }}
     env:
@@ -120,6 +131,130 @@ jobs:
           elif [ ${{ steps.container_scan.outcome }} == "success" ]
           then
             echo "### :rainbow: No vulnerabilities of HIGH or CRITICAL severity detected" >> container_scan_prcomment.json
+            exit 0
+          fi
+
+      - name: PR comment the container scan report
+        uses: mshick/add-pr-comment@v2
+        with:
+          message-id: trivy_container_scan
+          message-path: container_scan_prcomment.json
+
+      - name: After Step
+        if: ${{ inputs.after_step_command != '' }}
+        run: |
+          ${{ inputs.after_step_command}}
+
+  detect_dockerfile_paths:
+    runs-on: ubuntu-latest
+    if: ${{ inputs.is_monorepo_with_multi_dockerfile }}
+    name: Detect Dockerfile Paths
+    outputs:
+      matrix: ${{ inputs.dockerfile_paths =="" && steps.find_dockerfile_generate_matrix.outputs.all_dockerfile_paths_matrix || steps.generate_matrix.outputs.all_dockerfile_paths_matrix }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Find Dockerfile paths and Generate matrix JSON
+        if: ${{ inputs.dockerfile_paths =="" }}
+        id: find_dockerfile_generate_matrix
+        run: |
+          files=$(find . -type f -name 'Dockerfile' | sort | sed 's|^\./||')
+          json=$(printf '%s\n' "$files" | jq -R . | jq -s '{dockerfile_paths: .}')
+          echo "all_dockerfile_paths_matrix=$json" >> "$GITHUB_OUTPUT"
+          echo $all_dockerfile_paths_matrix
+      
+      - name: Generate matrix JSON
+        if: ${{ inputs.dockerfile_paths !="" }}
+        id: generate_matrix
+        run: |
+          echo "all_dockerfile_paths_matrix={
+                  "dockerfile_paths": ${{ inputs.dockerfile_paths }}
+                }" >> "$GITHUB_OUTPUT"
+          echo $all_dockerfile_paths_matrix
+
+
+containers_scan:
+    runs-on: ubuntu-latest
+    if: ${{ inputs.is_monorepo_with_multi_dockerfile }}
+    needs: detect_dockerfile_paths
+    container:
+      image: ${{ inputs.action_runner_container_image }}
+    env:
+      NPM_TOKEN: ${{ secrets.NPM_TOKEN != '' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
+    strategy:
+      matrix:
+        dockerfile_paths: ${{ fromJson(needs.detect_dockerfile_paths.outputs.matrix) }}
+        
+    steps:
+      - name: Before Step
+        if: ${{ inputs.before_step_command != '' }}
+        run: |
+          ${{ inputs.before_step_command}}
+
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.ref }}
+
+      - # Add support for more platforms with QEMU (optional)
+        # https://github.com/docker/setup-qemu-action
+        name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Docker Build
+        id: docker_build
+        env:
+          FINAL_DOCKER_BUILD_COMMAND: ${{ inputs.docker_build_command != '' && inputs.docker_build_command || format('docker build --build-arg NPM_TOKEN={0} -t --file ${{ matrix.dockerfile_paths } {1} .', secrets.NPM_TOKEN, inputs.docker_build_image_id) }}
+        run: |
+          echo $FINAL_DOCKER_BUILD_COMMAND
+          eval $FINAL_DOCKER_BUILD_COMMAND
+
+      - name: Creating Trivy report PR comment template file
+        run: |
+          cat <<EOF >> trivyreport.tpl 
+          | Package | Vulnerability | Severity | Status | Installed Version | Fixed Version | Title |
+          | ------- | ------------- | -------- | ------ | ----------------- | ------------- | ----- |
+          {{- range .}}
+          {{- range .Vulnerabilities}}
+          | {{ .PkgName | html }} | {{ .VulnerabilityID | html }} | {{ .Severity | html }} | {{ .Status | html }} | {{ .InstalledVersion | html }} | {{ .FixedVersion | html }} | {{ .Title | html }} |
+          {{- end }}
+          {{- end }}
+          EOF
+
+      - name: Trivy container vulnerability scan
+        id: container_scan
+        uses: aquasecurity/trivy-action@master
+        continue-on-error: true
+        with:
+          image-ref: ${{ inputs.docker_build_image_id }}
+          format: "template"
+          template: "@trivyreport.tpl"
+          output: "trivyreport.json"
+          exit-code: "1"
+          ignore-unfixed: true
+          vuln-type: "os,library"
+          severity: "CRITICAL,HIGH"
+          scanners: ${{ inputs.container_scanners }}
+          skip-dirs: ${{ inputs.container_scan_skip_dirs }}
+
+      - name: Create container vulnerability report
+        if: ${{ !cancelled()  }}
+        shell: bash
+        run: |
+          echo "# Trivy Container Scan" > container_scan_prcomment.json
+          if [ ${{ steps.container_scan.outcome }} == "failure" ]
+          then
+            echo "### :warning: Vulnerabilities detected\n Dockerfile: ${{ matrix.changed_dockerfiles }}\nThe following vulnerabilities of HIGH or CRITICAL severity has been detected in the code. Please resolve these before merging the pull request.<br><br>" >> container_scan_prcomment.json
+            cat trivyreport.json >> container_scan_prcomment.json
+            echo "::error::Vulnerabilities found! Find the scan report in the PR comment if this scan was triggered by PR"
+            exit 1
+          elif [ ${{ steps.container_scan.outcome }} == "success" ]
+          then
+            echo "### :rainbow: \n Dockerfile: ${{ matrix.changed_dockerfiles }}\n No vulnerabilities of HIGH or CRITICAL severity detected" >> container_scan_prcomment.json
             exit 0
           fi
 
